### ISSUE TITLE
我写了一篇one step 适配的 blog，希望可以采纳

### ISSUE THREAD

**Issue by BytesZero** [SmartisanTech/SmartisanOS-SDK#1]
博客地址如下：[http://blog.csdn.net/yy1300326388/article/details/52883789](http://blog.csdn.net/yy1300326388/article/details/52883789)

希望可以放到本项目的readme和官网中帮助到其他的开发者，感谢

**Comment by codingbyai** [comment]
已经加到README中了，谢谢。
